package functions

func ScoreCalc(inputKon, inputTeh []string) (map[string]int, map[string]int) {

	furnituurid := map[string]map[string]int{
		"Puittüübel keerdsooneline": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         100,
			"Avatav":         0,
			"Liimiga":        100,
			"Liimita":        0,
			"Monteeritud":    100,
			"Flatpack":       0,
			"Nahtav":         0,
			"Mittenahtav":    100,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   0,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  -100,
			"CNCjah":       100,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    0,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},

		"Läätsveeder": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         100,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         100,
			"Avatav":         0,
			"Liimiga":        100,
			"Liimita":        0,
			"Monteeritud":    100,
			"Flatpack":       0,
			"Nahtav":         0,
			"Mittenahtav":    100,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   0,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  0,
			"CNCjah":       150,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    -100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},

		"Konstruktorkruvi": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 100,
			"Seest Nahtav":   0,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  -100,
			"CNCjah":       100,
			"CNCei":        100,
			"LamelloJAH":   0,
			"LamelloEI":    100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"Mööblipolt + tapimutter": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 100,
			"Seest Nahtav":   100,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  -100,
			"CNCjah":       100,
			"CNCei":        100,
			"LamelloJAH":   0,
			"LamelloEI":    100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"Minifix + tüübel": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   100,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  -100,
			"CNCjah":       100,
			"CNCei":        100,
			"LamelloJAH":   0,
			"LamelloEI":    100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"Maxifix + tüübel": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   100,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  -100,
			"CNCjah":       100,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    0,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		}, "INVIS": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      0,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       0,
			"Nahtav":         0,
			"Mittenahtav":    100,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   000,

			"ServaPuurJAH": 100,
			"ServaPuurEI":  -100,
			"CNCjah":       100,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    0,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"Rafix": {
			"Kandev Kulg":    100,
			"Lagi Peal":      0,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       0,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   100,

			"ServaPuurJAH": 0,
			"ServaPuurEI":  100,
			"CNCjah":       100,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    0,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"Clamex P “LAMELLO”": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         100,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   100,

			"ServaPuurJAH": 0,
			"ServaPuurEI":  100,
			"CNCjah":       150,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    -100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"Tenso P “LAMELLO”": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         100,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         100,
			"Avatav":         0,
			"Liimiga":        100,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         0,
			"Mittenahtav":    100,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   0,

			"ServaPuurJAH": 0,
			"ServaPuurEI":  100,
			"CNCjah":       150,
			"CNCei":        0,
			"LamelloJAH":   100,
			"LamelloEI":    -100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"“DOMINO” puit": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         100,
			"Avatav":         0,
			"Liimiga":        100,
			"Liimita":        0,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         0,
			"Mittenahtav":    100,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   0,

			"ServaPuurJAH": 0,
			"ServaPuurEI":  100,
			"CNCjah":       150,
			"CNCei":        0,
			"LamelloJAH":   0,
			"LamelloEI":    100,
			"dominoJAH":    100,
			"dominoEI":     -100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"“DOMINO” KV-LR32": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         0,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         100,
			"Mittenahtav":    0,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   100,

			"ServaPuurJAH": 0,
			"ServaPuurEI":  100,
			"CNCjah":       150,
			"CNCei":        0,
			"LamelloJAH":   0,
			"LamelloEI":    100,
			"dominoJAH":    100,
			"dominoEI":     -100,
			"ovvoJah":      0,
			"ovvoEI":       100,
		},
		"”OVVO” Freesitav avatav": {
			"Kandev Kulg":    100,
			"Lagi Peal":      100,
			"Eerung":         100,
			"Vaheriiul":      100,
			"Vahesein":       100,
			"Ei Ava":         0,
			"Avatav":         100,
			"Liimiga":        0,
			"Liimita":        100,
			"Monteeritud":    100,
			"Flatpack":       100,
			"Nahtav":         0,
			"Mittenahtav":    100,
			"Valjast Nahtav": 0,
			"Seest Nahtav":   0,

			"ServaPuurJAH": 0,
			"ServaPuurEI":  100,
			"CNCjah":       150,
			"CNCei":        0,
			"LamelloJAH":   0,
			"LamelloEI":    100,
			"dominoJAH":    0,
			"dominoEI":     100,
			"ovvoJah":      100,
			"ovvoEI":       -100,
		},
	}

	valitudKonstrukt := map[string]bool{
		"Kandev Kulg":    false,
		"Lagi Peal":      false,
		"Eerung":         false,
		"Vaheriiul":      false,
		"Vahesein":       false,
		"Ei Ava":         false,
		"Avatav":         false,
		"Liimiga":        false,
		"Liimita":        false,
		"Monteeritud":    false,
		"Flatpack":       false,
		"Nahtav":         false,
		"Mittenahtav":    false,
		"Valjast Nahtav": false,
		"Seest Nahtav":   false,
	}

	valitudTehnoloog := map[string]bool{
		"ServaPuurJAH": false,
		"ServaPuurEI":  false,
		"CNCjah":       false,
		"CNCei":        false,
		"LamelloJAH":   false,
		"LamelloEI":    false,
		"dominoJAH":    false,
		"dominoEI":     false,
		"ovvoJah":      false,
		"ovvoEI":       false,
	}

	for _, ch := range inputKon {
		valitudKonstrukt[ch] = true
	}
	for _, ch := range inputTeh {
		valitudTehnoloog[ch] = true
	}

	konstruktsioon := make(map[string]int)
	tehnoloogia := make(map[string]int)

	for valik, onValitud := range valitudKonstrukt {
		if onValitud {
			for furnituur, skoor := range furnituurid {
				konstruktsioon[furnituur] += skoor[valik]
			}
		}
	}
	for valik, onValitud := range valitudTehnoloog {
		if onValitud {
			for furnituur, skoor := range furnituurid {
				tehnoloogia[furnituur] += skoor[valik]
			}
		}
	}

	return konstruktsioon, tehnoloogia

}
